dist: trusty

language: c

cache:
    - ccache

compiler:
    - gcc

before_install:
    - sudo add-apt-repository --yes ppa:vala-team
    - sudo apt-get update --quiet
    - sudo apt-get install --yes --force-yes build-essential libglib2.0-dev
      libyaml-dev valac valadoc

before_script:
    - ./autogen.sh --disable-valadoc
    - make

script:
    - make check
    - tests/libyaml-glib-parser -i
    - tests/example-invoice < tests/invoice.yaml
